
= Git Cheat Sheet

Git is the open source distributed version control system that facilitates GitHub activities on your laptop or desktop. This cheat sheet summarizes commonly used Git command line instructions for quick reference.

= Markdown Syntax

Markdown is a way to style text on the web.
You can control the display of the document; formatting words as bold or italic, adding images, and creating lists are just a few of the things we can do with Markdown.
Mostly, Markdown is just regular text with a few non-alphabetic characters thrown in, like # or *.

= GitHub Flavored Markdown

GitHub.com uses its own version of the Markdown syntax that provides an additional set of useful features, many of which make it easier to work with content on GitHub.com.

== Requirements

* Java JDK 8
* Apache Maven
* Git

== Build HTML and PDF output

[source, shell]
----
$ git clone https://github.com/opennms-forge/git-cheatsheet.git
$ cd git-cheatsheet
$ mvn clean package
----

The HTML and PDF file is build to `target/generated-docs/index.{html,pdf}`.
